---
- name: Add recent PHP
  shell: yes | add-apt-repository ppa:ondrej/php5
  sudo: true

- name: Add recent Node
  shell: yes | add-apt-repository ppa:chris-lea/node.js
  sudo: true

- name: Install PHP
  apt: name=php5-cli state=present update_cache=yes
  sudo: true

- name: Install NPM
  apt: name=nodejs state=present update_cache=yes
  sudo: true