---
- hosts: all

  vars:
    - workspace: ../workspace/

    - repos:
      - labs-json-api
      - labs-frontend

  roles:
   - { role: travis, when: ansible_os_family == 'Debian' }
   - { role: setup }
   - { role: github }
   - { role: api }
   - { role: frontend }
